spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3307/profile
    driver-class-name: org.mariadb.jdbc.Driver

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    
servlet:
  multipart:
    enabled: true
    max-file-size: 50MB
    location: /fileupload
    max-request-size: 50MB
    
file:
  root-path: /fileupload
  
mybatis:
  mapper-locations:
  - classpath:config/mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true